/// <reference types="Cypress" />

context('App', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000')
  })

  it('Should have proper header element', () => {
    cy.get('.page-header')
      .should('have', 'img')
      .should('have', 'nav')
    cy.get('.page-nav')
      .should('have', 'ul')
    cy.get('.page-nav a')
      .should('have', '25 People Protected')
    cy.get('.page-nav button')
      .should('have', 'Protect More People')
  })

  it('Should be able to open up the add people popup and add people', () => {
    cy.get('.page-nav button')
      .click()
      .should('have', '.modal')
    cy.get('.model')
      .should('have', '.modal-header')
      .should('have', '.modal-content')
    cy.get('textarea')
      .type('Ryan Clark USA 28 99.0')
    cy.get('input')
      .click()
    cy.get('App')
      .should('not.have', '.modal')
    cy.get('.page-nav a')
      .should('have', '26 People Protected')
  })

  it('The Protected people counter should increase', () => {
    cy.get('.page-nav button')
      .click()
      .should('have', '.modal')
    cy.get('.model')
      .should('have', '.modal-header')
      .should('have', '.modal-content')
    cy.get('textarea')
      .type('Ryan Clark USA 28 99.0')
    cy.get('input')
      .click()
    cy.get('App')
      .should('not.have', '.modal')
    cy.get('.page-nav a')
      .should('have', '26 People Protected')
  })

  it('The added User should be in the list', () => {
    cy.get('.page-nav button')
      .click()
      .should('have', '.modal')
    cy.get('.model')
      .should('have', '.modal-header')
      .should('have', '.modal-content')
    cy.get('textarea')
      .type('Ryan Clark USA 28 99.0')
    cy.get('input')
      .click()
    cy.get('App')
      .should('not.have', '.modal')
    cy.get('.page-nav a')
      .should('have', '26 People Protected')
    cy.get('.user-list-wrapper')
      .should('have', 'Ryan Clark')
  })

  it('A Users info should be able to be shown', () => {
    cy.get('.ContentWrapper')
      .get('.user-list-section')
      .should('have', '.user-list-section-top')
      .get('.user-list-section-top button')
      .first()
      .click()
      .get('.user-list-section')
      .should('have', '.hidden-text-container')
      .get('.hidden-text-container')
      .should('have', 'Age', 'Nationality', 'Privacy Risk')
  })
})
